### ISSUE TITLE
zoekterm1, zoekterm2, Geef hier een beschrijving van de pagina

### ISSUE THREAD

**Issue by KrijnHoetmer** [RaymondKorrel/bt#1]
Pas op met je standaard HTML boilerplate; als je vergeet verborgen metadata aan te passen is het misschien handiger om überhaupt die elementen niet te hebben :)

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by Raymond179** [comment]
Meta data aangepast incl. zoektermen en author

**Comment by KoopReynders** [comment]
done
