### ISSUE TITLE
Zoomen op (kleine) touch devices werkt niet

### ISSUE THREAD

**Issue by KrijnHoetmer** [RaymondKorrel/bt#2]
Waarom mag ik niet inzoomen op mijn telefoon? Sommige thumbnails zijn interessant genoeg om even nader te inspecteren.

Zet zoomen alleen uit als je écht een goede reden hebt, en zet dit al zeker niet in je standaard HTML boilerplate ajb.

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by Raymond179** [comment]
Viewport settings aangepast zodat gebruiker kan zoomen

**Comment by KoopReynders** [comment]
done
