### ISSUE TITLE
Heading structuur kan beter

### ISSUE THREAD

**Issue by KrijnHoetmer** [RaymondKorrel/bt#3]
`<h2>` en `<h3>` gebruik je, maar volgens mij ontbreekt er nog een `<h1>`.

En zijn die `<li class="letter">` niet ook gewoon headings? Denk ook aan mensen die de structuur nodig hebben om je demo te kunnen gebruiken.

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by Raymond179** [comment]
Heading structuur aangepast. De hulpletters zijn nu h2's en de list items hebben een h3.

**Comment by KoopReynders** [comment]
done
