### ISSUE TITLE
alt attributen misschien ietwat gekkig

### ISSUE THREAD

**Issue by KrijnHoetmer** [RaymondKorrel/bt#4]
Waarom heb je de voornamen van de personen in de `alt` attributen geplaatst? Verplaats je in iemand die ze voorgelezen krijgt. Wil je dan bijvoorbeeld “Raymond Raymond Korrel” horen? Is het überhaupt relevant om iets bij die afbeelding te horen?

En is het bij de iconen relevant om te horen dat het een icoon is? Ook hierbij: “Email icon andy.van elderen@example.com” — is dat echt wat je bedoelt?

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by Raymond179** [comment]
Relevante alt namen toegevoegd. Bijvoorbeeld bij het email icoon, het woordje icon weggehaald zodat de screenreader een logishe text voorleest

**Comment by KoopReynders** [comment]
done
