### ISSUE TITLE
CSS bevat ook @import voor font?

### ISSUE THREAD

**Issue by KrijnHoetmer** [RaymondKorrel/bt#5]
In zowel je HTML als je CSS refereer je naar `https://fonts.googleapis.com/css?family=Roboto:400,100,700`; is dat de bedoeling?

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by Raymond179** [comment]
Google fonts alleen in css geimporteerd en weggelaten in html

**Comment by KoopReynders** [comment]
done
