### ISSUE TITLE
Volgorde van prefixed properties in CSS

### ISSUE THREAD

**Issue by KrijnHoetmer** [RaymondKorrel/bt#6]
Let er bij het gebruiken van prefixes op dat je de volgorde goed zet. Zoek vooral naar wat voorbeelden van hoe dat bij `linear-gradient` anders helemaal verkeerd kan gaan.

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by Raymond179** [comment]
Volgorde van prefixes veranderd. Als laatste de regel zonder prefix

**Comment by KoopReynders** [comment]
done
