### ISSUE TITLE
Hoe open ik de extra info zonder muis?

### ISSUE THREAD

**Issue by KrijnHoetmer** [RaymondKorrel/bt#7]
De batterijen van mijn muis zijn leeg; hoe open ik de info-kaartjes?

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by Raymond179** [comment]
Wanneer een list item geselecteerd is, kan op enter gedrukt worden om het te openen. Dit heb ik gedaan door er een <button> van te maken

**Comment by KoopReynders** [comment]
done
