### ISSUE TITLE
Feature detection in JS ontbreekt

### ISSUE THREAD

**Issue by KrijnHoetmer** [RaymondKorrel/bt#8]
Je hebt supervette oldskool code geschreven om zoveel mogelijk browsers mee te krijgen—respect!—maar wat als een browser zelfs `getElementsByTagName` niet ondersteunt? Probeer nog even een feature detect toe te voegen, zodat je in ieder geval geen JS errors krijgt (kijk bijvoorbeeld hoe de Cutting the Mustard check werkt). Gewoon om te laten zien dat je dat principe ook onder de knie hebt.

**Comment by KrijnHoetmer** [comment]
`alert("Your browser doesn't support this website")` - oh, but it does, perfectly! :) Die `alert()` is niet nodig, werkt alleen maar frustrerend; je laat mensen daarmee denken “Huh, wat mis ik dan?!”, terwijl je gewoon bij alle informatie kunt. Die `if` is wel goed, want dat voorkomt een foutmelding. `else` case gewoon lekker laten rusten. Top!

**Comment by KoopReynders** [comment]
done
